### ISSUE TITLE
Alpha Release: Build for Android

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#10]

**Comment by gokr** [comment]
Build now works, for the alpha I am good with a self signed apk. Then someone needs to mess with doing things properly.

**Comment by gokr** [comment]
I think the current build is fine, no? Self signed etc, I could of course investigate signing but... more important stuff to do.

**Comment by rtaibah** [comment]
I am leaving this open until we build the final alpha-release to the
public. The current one isn't the latest, we need to remove the BTC icons
for example.
