### ISSUE TITLE
Missing warning of loosing accounts when importing a seed

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#101]
There should be a warning (and passwd?) that this action will disable all  accounts present, similar the "type: clear keys" in rai_wallet.

**Comment by gokr** [comment]
There is now a warning, but I find the text confusing.

**Comment by stefonarch** [comment]
The warning could pop earlier, or maybe better a fixed text about import from backup AND a final warning
![schermata-21-08-19-29](https://user-images.githubusercontent.com/10681413/36467649-f8a9198c-16df-11e8-9175-95d825e1ef0a.png)

I think too this text should be revisited, proposal:

> Importing a wallet will overwrite your existing wallet and accounts, if you have funds in your actual wallet double check to have the backup from your seed or empty it first

**Comment by gokr** [comment]
I agree, will fiz

**Comment by gokr** [comment]
Added cautionary text above, and tweaked the warning popup to be more brief as suggested (with some tweaks). Closing.
