### ISSUE TITLE
Feature suggestion: loading icon when starting

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#102]
When connection is lagging none of the  accounts are displayed, a text "connecting...." would be better than showing an   empty account.

**Comment by rtaibah** [comment]
We already have a splashscreen. Is this what you mean?

**Comment by stefonarch** [comment]
It's parent/duplicate of https://github.com/getcanoe/canoe/issues/125
If no connection (or lagging connection ) it hangs   forever  on "decrypting wallet file..."
At the time writing it showed empty accounts, this has changed
