### ISSUE TITLE
Second account shows zero balance when imported from seed

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#103]
Steps to reproduce:
- Create a second account, send some nano to both, open  addresses in blockexplorer
- Import the same seed; the first account will display correct balance
- Create second account, it will have the same address as before but show zero balance.

(checked twice)

When sending after that something from first to second account the transaction will be pending.
When sending from first account after that it will not be broadcasted.

(checked once...)

**Comment by gokr** [comment]
Yes, can you repeat the above - but after recreating the second account - can you try Settings->Advanced->Repair ? And see if that will show proper balances.

**Comment by stefonarch** [comment]
I saw that option first but  did not think of it, it works.

**Comment by gokr** [comment]
Ok, cool. So yeah... that operation "pulls in the truth" from the lattice. It's called on seed import BUT... it's not called on subsequent account creations, so... yeah, I should probably implement doing that "per account".

**Comment by gokr** [comment]
Fixed now. It now calls resetChain when a new account is created - and thus pulls in old blocks from lattice.
