### ISSUE TITLE
Wrong value display when sending nano between accounts

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#106]
In the last screen the sending amount (1Nano) is displayed like that:
![schermata-12-19-09-49](https://user-images.githubusercontent.com/10681413/36112024-8110e8ae-1028-11e8-93d1-b953033b2496.png)

**Comment by Stormtv** [comment]
The rate calculations are a little messed up. The the rate service needs to be transferred over

**Comment by rtaibah** [comment]
Duplicate of #58

**Comment by stefonarch** [comment]
Fixed by https://github.com/getcanoe/canoe/commit/e0d0b337114e61958ae7da7442fcb4a428fd7020
