### ISSUE TITLE
Password shouldn't be asked before a minute

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#108]
This showed up on discord already but it's just to make sure no-one forgets before beta...

**Comment by rtaibah** [comment]
Can you elaborate more? What is the behavior you are suggesting?

**Comment by ceddup** [comment]
Well, this is covered by Gokr blog post here https://getcanoe.io/2018/02/11/security-in-beta.html
So this ticket could be deleted.

Still, having to type the password everytime the Android app goes background is a pain for testing/using the app on Android. 

So, if we need to make beta available ASAP, we must not stay like this.

**Comment by rtaibah** [comment]
Merge this into #95
