### ISSUE TITLE
After wallet import, home page (tab-home.html) doesn't refresh properly

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#110]
This is really scary for the user.  

You get to see 'Create a new Nano wallet' on home page. So one's first thought is that the Nanos are gone (you backed it up, reinstalled, entered wallet and pasword and... nothing)
Switching tabs doesn't help either. One needs to send some Nanos or restart the app. beta IMHO (I'll try to take a look).

This happens both on Android and webapp, and both on onboarding wallet import and in-app wallet import

**Comment by gokr** [comment]
I tried for a while to fix... but got tired. I added a rootScope event to
listen for finished import - so that view is updated. For some reason it
doesnt fully work.

Den tis 13 feb 2018 20:44ceddup <notifications@github.com> skrev:

**Comment by gokr** [comment]
Fixed now.

**Comment by stefonarch** [comment]
It's not ok still,  importing a seed from first screen or later it shows only the first account:
default account 0.00 NANO

Recreating manually second account show 0.00

When reload and re-login it shows for 2 existing accounts
1,00 = 7 euro
0.00

Repair helps at the end.

**Comment by ceddup** [comment]
I think my last PR fixes it
would you be so kind to test it ?

**Comment by stefonarch** [comment]
It's better but still needs re-login, and repair hangs when doing it directly after import.
