### ISSUE TITLE
Something going wrong with some alternative currencies

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#114]
I'm big on currencies like the ones used in Venezuela and Myanmar. These people are struggling and would sure use Canoe.
If one goes from dollard to MMR (Myanmar) from the alternative currency setting and then send Nanos : everything goes right, NANO is well converted to MMK.

But, after reloging (wallet) or even if you wait a minute (profileService.updateRate), then convertion is gone

This makes the app less usefull for people there
It has something to do with how https://api.coinmarketcap.com behaves
But it works, sometimes, pretty frustrating...

I can reproduce it but not fix it, so I guessed I would make a ticket

Of course not urging for beta

**Comment by gokr** [comment]
I am rewriting rateService for beta so lets revisit after that.

Den ons 14 feb 2018 01:27ceddup <notifications@github.com> skrev:

**Comment by ceddup** [comment]
I found the reason for this bug.
rateService gets it's rates from https://bitpay.com/api/rates -> bitpay knows MMK rate, see https://bitpay.com/api/rates/MMK
But profileService gets it's rate from coinmarketcap.com that doesn't know about MMK see, no 'price_mmk' entry : 
https://api.coinmarketcap.com/v1/ticker/raiblocks/?convert=MMK
Whereas eur is fine, we get the 'price_eur' entry :
https://api.coinmarketcap.com/v1/ticker/raiblocks/?convert=EUR

Anything wrong with using bitpay over coinmarketcap ?

**Comment by schenkty** [comment]
@ceddup it looks like bitpay rates are only for bitcoin. the MMK price looks to be an issue with coinmarketcap in general. May have to submit something to them to see if they can fix it

**Comment by gokr** [comment]
@ceddup Can you check if this one can be closed now?

**Comment by ceddup** [comment]
Ok, will do this evening

**Comment by stefonarch** [comment]
I think this is fixed, it happens with high deflationary currencies
![mmk](https://user-images.githubusercontent.com/10681413/36475212-41ae9912-16fa-11e8-9286-fe795553b69f.gif)

**Comment by ceddup** [comment]
We can close this ticket to me.
The account balance convertion (≈ 5 EUR) doesn't display after onboarding, but that should be another ticket imho

**Comment by stefonarch** [comment]
Convertion does never show for 0 balance:
![schermata-01-07-52-12](https://user-images.githubusercontent.com/10681413/36830832-8e727f1c-1d25-11e8-8e09-3cea89a71d60.png)

**Comment by ceddup** [comment]
Can be closed I think (fixed 0 Nano convertion)
