### ISSUE TITLE
No check for existing account names

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#118]
It's possible to create 5 accounts "Joe".

**Comment by gokr** [comment]
Yeah, it's actually just an attribute, not a unique id. But... I agree we should not allow duplicates for usability sake.

**Comment by stefonarch** [comment]
Did not test for multiple alias, but there a check is needed sure.

**Comment by gokr** [comment]
Fixed. Aliases will be handled in other issue, lots of work left there.
