### ISSUE TITLE
Colors of accounts not fetched in receive tab

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#124]
When different  colors are set for accounts they are displayed everywhere except in receive tab which shows always .default color.
~~Related somehow: choose random new color when creating new accounts automatically?~~ See: https://github.com/getcanoe/canoe/issues/137

**Comment by rtaibah** [comment]
Created a new issue for your second point https://github.com/getcanoe/canoe/issues/137

**Comment by stefonarch** [comment]
Fixed
