### ISSUE TITLE
Swedish characters åäöÅÄÖ get messed up

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#130]
I think we are getting strings inserted as 8859-1 or something, and needs to be converted to UTF8 at some point. If I enter swedish characters in Account names, they end up barfy when wallet is reloaded from localstorage (JSON).

**Comment by ceddup** [comment]
Same problem with french specific characters

**Comment by ceddup** [comment]
I tried to tackle that one for a little while. No luck. For now I just translate 'Default account' to something without special characters ;-)

**Comment by gokr** [comment]
Fixed now.
