### ISSUE TITLE
Import wallet allows weak password

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#135]
There is no password strength check when importing a wallet.

**Comment by gokr** [comment]
Ah, eight

**Comment by rtaibah** [comment]
We agreed that we will not enforce any requirements except for 8 character lower limit. In the future we can enforce not allowing common passwords, with something like [this](https://cry.github.io/nbp/).

**Comment by ceddup** [comment]
We should close
Why should Canoe require anything to someone who desperatly wants to recover his money ?

**Comment by stefonarch** [comment]
That doesn't make sense, in onboarding Canoe ask for 8 letters, in "Import from seed" allow 3?

**Comment by gokr** [comment]
Just make sure it's 8 letters required in both UIs.

**Comment by Stormtv** [comment]
Easy fix added an 8 character minimum
