### ISSUE TITLE
First time user experience

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#136]
This did not work properly the last three times I tried. It may work on the current dev apk.
Still, this is a test we must do again before delivering beta :
- Create a wallet from scratch (new phone or Canoe totally uninstalled)
- Do Onboarding -> Check that the final home screen displays a new Default account
- Push receive -> Check that QR code is visible
- Send some Nano (small amount) -> Check that the money goes through to the new Canoe account
- Send some Nano back

**Comment by rtaibah** [comment]
I am not following? What is the expected behavior vs. actual?

**Comment by ceddup** [comment]
Ok, this is working now. BUT, 3 times, in different situations, the past few days, I got some friends to try Canoe. Everytime (no luck), this simple scenario did not work.
So, I described it so we can try it (really from scratch) one last time before we release beta. This way we'll make sure not to start really bad. We never know what can break and onboarding from scratch is not a thing we do all the time as devs. Do you see what I mean ?
So, I would leave this one open before release (Even though it could be considered 'bad press')

**Comment by ceddup** [comment]
Closing, just tested 😉
