### ISSUE TITLE
Gravatars don't automatically update

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#150]
When adding an email to an account in the addressbook, the avatar does not automatically updates (if exists in Gravatar.) A user needs to navigate away from the Addressbook and come back again to see the avatar applied.

**Comment by Stormtv** [comment]
I believe I fixed this when I added in aliases last night.

**Comment by rtaibah** [comment]
With Aliases, Gravatars are completely removed? What if someone doesn't
create an alias?

**Comment by gokr** [comment]
I would hope it wasn't removed?

**Comment by Stormtv** [comment]
It was not removed, but if the person has an alias the avatar of the alias takes priority over the gravatar if that makes sense. I did fix the bug with the gravatar icon not showing up after editing the email though also.
