### ISSUE TITLE
Remove Import Warning, if User is Coming from Onboarding

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#151]
There is no point to have that warning if a user is coming from onboarding since there is no wallet in the app anyways. 
![screen shot 2018-03-01 at 10 59 42 am](https://user-images.githubusercontent.com/707668/36833277-e96ddf78-1d3f-11e8-9992-b38e79c83f97.png)

**Comment by ceddup** [comment]
Fixed it
