### ISSUE TITLE
Cleanup unlock screen

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#153]
The unlock screen is kind of overloaded with emergency stuff.

Putting "restore from seed, forgot password" to a second screen which will show up only  after 1 or 2 failed login attempts would be  a solution.

**Comment by rtaibah** [comment]
That doesn't make sense. So if I know I don't know the password, I have to
deliberately input the password wrong? Think of it as an login form.

I'll look into cleaning/simplifying it though.

**Comment by stefonarch** [comment]
That is a point, so a small "Don't remember pwd?" makes sense there, but in 99% of use cases you know the passwd and don't want to restore from seed

**Comment by stefonarch** [comment]
Just remove "Forgot your passwd" could do too.

**Comment by ceddup** [comment]
We should close for now imho. Maybe make another, clearer tiket for v1
