### ISSUE TITLE
Missing Canoe icon on tab in desktop Chrome browser (win10)

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#154]

**Comment by rtaibah** [comment]
Screenshot?

**Comment by Stormtv** [comment]
I think he is talking about The fav icon in all browsers

**Comment by rtaibah** [comment]
In that case, users wouldn't typically use Canoe in a browser. Making this
bug invalid.

**Comment by Stormtv** [comment]
Eventually I would like to have a web wallet of canoe

**Comment by ceddup** [comment]
![image](https://user-images.githubusercontent.com/10496246/36929512-d7fadf5e-1e91-11e8-91f8-b01187964065.png)

**Comment by stefonarch** [comment]
Creating www/img/app/favicon.ico solves (on linux)
[favicon.zip](https://github.com/getcanoe/canoe/files/1780459/favicon.zip)

**Comment by ceddup** [comment]
Stef and I fixed that one, Rami said he would shrink even more.
Test & close ?

**Comment by stefonarch** [comment]
Shrinked, both transparent and <1M  https://github.com/getcanoe/canoe/issues/164
