### ISSUE TITLE
Refresh transaction view when incoming receive block

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#160]
So you don't have to come back to home page and click again on the account to see the last Nano received

**Comment by rtaibah** [comment]
Though keeping 'pull to refresh' is also a good idea since it gives the user a sens of control. Even if it doesn't do anything.

**Comment by ceddup** [comment]
I fixed this one. Can you test and close ?

**Comment by rtaibah** [comment]
@ceddup Not working for me.

**Comment by ceddup** [comment]
Well it works here (Chrome & Android)
Can you test again ?

**Comment by ceddup** [comment]
Can we close ?
