### ISSUE TITLE
Sending to the same account renders the Nanos 'lost'

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#164]
By pure luck, I discovered this. Sending to the same account, the Nano's are 'lost'. Since this was a coincidence discovery, we should try to reproduce it first, as I cannot confirm that this is what actually happened.

So whoever confirms it, please just leave a comment.

![group](https://user-images.githubusercontent.com/707668/37023478-26254bea-2137-11e8-9b94-5e962fcf2246.png)

**Comment by stefonarch** [comment]
Did you use "to account" or alias? Cannot reproduce on Desktop linux localhost, it just comes in.

**Comment by stefonarch** [comment]
I think it's impossible now, it  makes two blocks when inserting the address, and using "to account" the sending account is always removed from the possible receiving accounts
