### ISSUE TITLE
Using "Refund" send tab does never clear again.

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#166]
txn view → click an receive entry → "Refund" to sent back and don't sent it.
Back to home tab → send will show the refund screen ready to sent, needs relogin to "free" it.

**Comment by ceddup** [comment]
Ok this is on me

**Comment by stefonarch** [comment]
FIxed by https://github.com/getcanoe/canoe/commit/665529ea243496314164c887e503e40e79194029 thanks :)
