### ISSUE TITLE
Issue when account has already nanode alias

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#167]
First there is no icon for the account with nanode alias.

And there is a strange issue when sending to aliases. Funds arrive in the wallet but not in the corresponding alias.
In one test funds went to the first account.
In another test all  funds went to the newest account with no alias set.
* 4 accounts, the first has an nanode alias set and no icon
* 2 other accounts with different alias set for each
* one fresh account

Sending funds using alias @1 and@2 get both pocket by the fresh account

Sending to wallet address works as usual.

**Comment by ceddup** [comment]
Is that fixed ? Or still remains with 5 account ?

**Comment by stefonarch** [comment]
It looks like something has changed when importing from seed, icon is there.
But all the aliases created once are pointing  now to the 5th account, could test again with new alias later.

**Comment by stefonarch** [comment]
Verified with new aliases, cannot reproduce.
Probably this situation is due to an wallet file import in early stage of aliases.
