### ISSUE TITLE
Add donation section to settings

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#17]
Should be in a section on it's own under 'Share Canoe' and opens to the send page with our address prefilled.

**Comment by gokr** [comment]
I am going to:
* Get postfix onto getcanoe.io
* Register a donation email with gravatar
* Add a donation contact in the Addressbook
* Add a "Donate" entry in Settings that opens Send page with this contact.

**Comment by gokr** [comment]
Done.
