### ISSUE TITLE
Add setting to change representative

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#178]
Under settings there should be an easy way to change the representative of the Wallet. Both a text field with scan ability to enter an account number, or using a list to select among our "selected trusted examples of reps". This list should be populated via dynamic config over retained MQTT message (other issue), so that we can change it dynamically.

**Comment by ceddup** [comment]
Closable ? I tested, it worked

**Comment by gokr** [comment]
Yeah, this is enough for beta but we also need a setting "default rep for new accounts"
