### ISSUE TITLE
Scan freezes on invalid QR code

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#184]
When scanning an invalid QR code it just freezes.
![invalidqrcode](https://user-images.githubusercontent.com/10681413/37217569-2fbaafa4-23be-11e8-9042-7baa6df6e79c.png)
Issue in address book add, scan from tab, sent to,  after recognizing QR code it does not continue, just blocks there.

Only  in "change representative" it gives  the correct warning.

![schermata-09-17-25-01](https://user-images.githubusercontent.com/10681413/37217837-f089424a-23be-11e8-9f3b-8762b68e5cbd.png)

**Comment by stefonarch** [comment]
Can still reproduce the issue in "scan" in the  bottom bar and "send", alert is working in "add adress book" and "change rep"

**Comment by gokr** [comment]
Think this is fixed, do test and verify

**Comment by stefonarch** [comment]
Fixed, but other alert here: "Unrecognized data"
https://github.com/getcanoe/canoe/commit/f764ca5470f472bbbbe821af0a64be985e412576
