### ISSUE TITLE
Move "session log" into "Advanced"

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#187]
More appropriated IMO.

**Comment by rtaibah** [comment]
The "Advanced" section is actually "Advanced Settings" ...."Session logs" aren't settings.

**Comment by ceddup** [comment]
And how to buy could move under help also

**Comment by stefonarch** [comment]
I see, not a setting. 
@ceddup howtobuy goes to howtobuy page, help to FAQ

**Comment by ceddup** [comment]
@stefonarch I'm talking about the link in settings, so the settings page doesn't have too many lines

**Comment by stefonarch** [comment]
So a submenu in "Help"?

**Comment by ceddup** [comment]
That's what I meant yeah
