### ISSUE TITLE
You kinda get stuck on alias screen when onboarding. At least on Android

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#190]

**Comment by rtaibah** [comment]
I never got stuck. Is it the buttons going out of the view?

**Comment by ceddup** [comment]
Yes, you can't see the buttons, they are hidden by the keyboard and if you don't fill the email correctly (like Ceddop@gnail.com for exemple) validation button on the keyboard does nothing.

**Comment by Stormtv** [comment]
I'll grab my android device and see if I can replicate this.

**Comment by ceddup** [comment]
I think just changing upper case to lower case on the fly could do the trick.
The thing is that the Android keyboard (at least in french) puts the first letter in upper case and it's tad twisted to finally get a lower case

**Comment by rtaibah** [comment]
Yes just noticed this. The Alias does not accept uppercase chars, however the Alias field auto-capitalize. I don't think this is what @ceddup meant with this issue, but we might as well fix this and remove the auto-capitalize from the field.

**Comment by Stormtv** [comment]
Good catch I’ll make sure it’s lowercase

**Comment by Stormtv** [comment]
Alright I added auto capitalize to off for those fields and made it so the view scrolls on lower resolution devices. Not sure if I need to programmatically force it to lowercase though?

**Comment by ceddup** [comment]
I can't test until a new apk is built but from the code I read from your push, it feels like the 'email' type should get us the best UX possible...
I'll tell you as soon as I get to test

**Comment by ceddup** [comment]
We can close this one
