### ISSUE TITLE
Max amounts demanding passwords

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#207]
Implement logic around asking for password when max amounts are reached, as described in security article:

> Max amount to send in a single send (set in user choice of currency), without requiring password
> Max amount to send during x hours (set in user choice of currency), without requiring password

**Comment by rtaibah** [comment]
Can we add to the security preferences some sort of %?

So allow only up to 50% of my total Nano to be transferred without a password. For example.

**Comment by gokr** [comment]
Scrappin this idea
