### ISSUE TITLE
Importing wallets with 200+ blocks, the canoe world ends 

### ISSUE THREAD

**Issue by schenkty** [getcanoe/canoe#212]
Just compiled the iOS app and web app, I can not import my wallet with 200+ blocks without canoe just not working. It imports and lets me login but then I don't have my account in there and I can't create a new account inside the wallet.

Hope this helps :/

Thanks,
Ty

**Comment by gokr** [comment]
Need a log or somethinv

**Comment by gokr** [comment]
This is actually #232 - closing this one. Has nothing to do with iOS nor 200 blocks.
