### ISSUE TITLE
Improve sent  confirmation

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#228]
As suggested in reddit, taking address or address book entry
![improve sent](https://user-images.githubusercontent.com/10681413/38026697-6c0d9f10-328d-11e8-8d44-5d61bac8569a.png)

**Comment by Stormtv** [comment]
The more I play with this the less I actually think it is a good idea. The idea of this screen is to just be flashy. Adding information here takes away from the main objective of this screen. People can always review their transaction in the transaction viewer. I'd love to hear other thoughts on this

**Comment by rtaibah** [comment]
I agree. With Tyler. It's whole purpose is flashiness, adding info will
take that away. I would close and abandon this if you guys agree.

**Comment by Stormtv** [comment]
I'm closing this per discussion above. I think #226 will improve the overall feel of sending.

**Comment by stefonarch** [comment]
If it's flashy let it be flashy so, an idea idea was to add a timeout here so that user don't have to click it away, maybe switch to txn history of the account that sent it.

**Comment by Stormtv** [comment]
Okay I agree that it should auto close after a short timeout. Also I like the idea of a "View this transaction" which opens the transactions explorer for that account.
