### ISSUE TITLE
win7 desktop view not adjusting. screenshots

### ISSUE THREAD

**Issue by superkryptonite** [getcanoe/canoe#230]
see screen shot below. when i click get started on first page, the next page does not adjust correctly. Canoe desktop beta on windows 7
![canoe 1](https://user-images.githubusercontent.com/37878285/38044373-75fe4398-32b1-11e8-869e-c5a0d286a3a1.JPG)

![canoe2](https://user-images.githubusercontent.com/37878285/38044076-a491e1c0-32b0-11e8-91fe-fbc450185008.JPG)

**Comment by Stormtv** [comment]
Thanks for the ticket we have fixed this bug already and it will be included in the next build!
https://github.com/getcanoe/canoe/issues/222
