### ISSUE TITLE
iOS password input is not displayed properly

### ISSUE THREAD

**Issue by Stormtv** [getcanoe/canoe#231]
![Image of bad pwd field](https://cdn.discordapp.com/attachments/398139206880460800/428612070108430336/Screen_Shot_2018-03-28_at_1.50.56_PM.png)

**Comment by Stormtv** [comment]
I was able to fix the centering of the placeholder text by increasing the line-height to match the font-size. The input field is still only 50% width on iOS including on a real iOS device. I couldn't figure out what was causing it

**Comment by rtaibah** [comment]
Did you consider what this change does to other devices?

I would recommend using iOS classes for changes. I think there is an
`.for-ios` class in ionic.

**Comment by Stormtv** [comment]
It didn’t impact anything besides the iOS/Safari placeholder text.

**Comment by Stormtv** [comment]
Fixed this by redoing the page I hope.
