### ISSUE TITLE
Unable to export seed of other accounts that were added

### ISSUE THREAD

**Issue by Stormtv** [getcanoe/canoe#235]
Any accounts besides the first one do not have a way to access the seed.

**Comment by gokr** [comment]
What does this mean?

**Comment by Stormtv** [comment]
When you create additional accounts there is no way to export the seed of the additional accounts. The export seed option only gives you the seed of the original account.

**Comment by gokr** [comment]
This is a misconception, closing.

**Comment by rtaibah** [comment]
Well can you explain why it's a misconception?

**Comment by gokr** [comment]
Ok, so... there is only ever one seed per wallet. Seeds aren't "per account". All accounts are created deterministically in the same order from a single seed.
