### ISSUE TITLE
Misaligned page after clicking 'Get Started' on Linux

### ISSUE THREAD

**Issue by VenKamikaze** [getcanoe/canoe#236]
Firstly, I am running: 
ArchLinux with the Cinnamon Desktop environment (if it matters)

On first run of Canoe 0.3.4 on linux (the zip, not the AppImage), I clicked 'Get Started' and noticed the next displayed page seemed to be misaligned and kind of between two steps. 

See attached images

![canoe1](https://user-images.githubusercontent.com/2378905/38079541-51e9c298-337e-11e8-8bf5-ab240fb74ca2.png)
![canoe2](https://user-images.githubusercontent.com/2378905/38079547-53f8a31a-337e-11e8-86ad-3e54fc486796.png)

I then resized the window, and clicked back, then forwards, and it displayed OK:
![canoe3_after_resize_and_back_and_forward](https://user-images.githubusercontent.com/2378905/38079560-5d4ca4f2-337e-11e8-9be6-8b294256c1a4.png)

Here is the exact build I'm on:
![canoe5-version](https://user-images.githubusercontent.com/2378905/38079577-66f18c3e-337e-11e8-8cae-dea207f73d94.png)

**Comment by gokr** [comment]
This has been reported and also fixed, will be in next build! Thanks

**Comment by VenKamikaze** [comment]
Apologies, I looked at open issues and forgot to check closed ones!
Thanks and its a great wallet :)
