### ISSUE TITLE
Double balance after wallet restore

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#240]
"There is a bug in import wallet flow, when you click on "go to onboarding" and restore your wallet, it shows you have twice the earlier amount."

I suspect balance cache?

**Comment by gokr** [comment]
I think I fixed this one, would love if someone could verify that.

**Comment by stefonarch** [comment]
Could not reproduce  anymore.

**Comment by stefonarch** [comment]
> * Fixed deadlock when shutting down the node

Is not fixed this here.

**Comment by gokr** [comment]
Eh... this last comment - what is that? So I can close this one then?

**Comment by gokr** [comment]
Closing this one for now, seems to be fixed.
