### ISSUE TITLE
.desktop file for AppImage/Linux does not bump version

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#241]
Should automatically update when version is bumped.
`X-Canoe-BuildId=0.3.5
`

**Comment by stefonarch** [comment]
No
https://github.com/getcanoe/canoe/blob/master/resources/canoe/linux/canoe.desktop

**Comment by gokr** [comment]
Ah, ok, right. So... the build script "burns" in the correct version when building, but its not committed. I will figure out how to handle it better.

**Comment by gokr** [comment]
Closing this since... the build actually fixes it, but does not commit it automatically.

**Comment by stefonarch** [comment]
So no commits needed anymore?

**Comment by gokr** [comment]
Nah. When I build it get's set properly.

**Comment by stefonarch** [comment]
But when I build locally here not ;)
