### ISSUE TITLE
Backup Seed

### ISSUE THREAD

**Issue by Colmy** [getcanoe/canoe#262]
Could a way to split the seed into 4 digits with a divider in between be added so that it's easier to write down the seed?

**Comment by stefonarch** [comment]
Not bad idea, the other approach is the 24 words mnemonic thing. Also splitting the seed there will be still 16 4-char units to copy correctly. I recommend testing the written seed, to check if it's working.

**Comment by gokr** [comment]
Changed to 4 lines of 4 groups, removed ellipsis CSS (no idea why we had that) and removed copy/paste support since that's dangerous.
