### ISSUE TITLE
Transfer to account: impossible selecting accounts after third

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#263]
![schermata-20-23-01-19](https://user-images.githubusercontent.com/10681413/39073647-c6e08b0a-44ee-11e8-9d73-4752c961b568.png)
There is no possibility to scroll the accounts if list of address book is large, 4th 5th accounts are hidden by send account info. Here is account 5 hidden.

**Comment by Stormtv** [comment]
https://github.com/getcanoe/canoe/commit/368a86237b551ec71db40582d9c50b3f6e2fd300

Fixed it I hope
