### ISSUE TITLE
Allow seed import also if lowercase

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#265]
Some people refer to lowercase seed exported by official beta dsktop wallets.
Other use case: using some seed generator

**Comment by stefonarch** [comment]
This could eventually be combined with https://github.com/getcanoe/canoe/issues/262 ? Add and trim empty spaces?

**Comment by gokr** [comment]
Fixed in https://github.com/getcanoe/canoe/commit/34b388cd3f55c016480a52905931316793d3c215
