### ISSUE TITLE
Donate address book entry seems to be broken

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#267]
cryptocode says: "address book, donate, send, @[object Object] in recipient field"

I suspect this only happens with a new wallet, my old one on desktop works fine. Alias remnant?

**Comment by stefonarch** [comment]
Cannot reproduce this with a genuine wallet.

**Comment by gokr** [comment]
I reproduced it on my phone, but not on my desktop. I think Tyler can figure it out, since I think it has to do with aliases. Another strange thing was that I couldn't edit the address field of the "Donate Canoe" entry in the address book - on my phone. And "Save" button never got active. although the other fields were editable. But I could delete the entry.

**Comment by stefonarch** [comment]
Donations go trough, it's only a display issue
https://www.nanode.co/block/8129648F7969931679614ED40945714272C2C0C1D092AF9D02DE93C3A757654D

Btw import that wallet/accoun in the server node that donations are pocketed automatically? Sending to my node works that way.

**Comment by Stormtv** [comment]
Easy fix, all that alias code is still in the system just waiting to be turned on ;)
