### ISSUE TITLE
Stateblocks are malformed in the TX History

### ISSUE THREAD

**Issue by Stormtv** [getcanoe/canoe#268]
Need to add proper parsing of State blocks and not break existing TX History

**Comment by Stormtv** [comment]
Works fine now when I try to test it on my dev version but on my mobile wallet the TX information is wrong. My sends show up as receives sometimes.

**Comment by stefonarch** [comment]
I did a send from test backend/state blocks to nanovault, it went trough but "view on nanode" in history goes to a non existing block hash
Probably another issue.

**Comment by gokr** [comment]
I do wonder if this is still reproducable.

**Comment by stefonarch** [comment]
recompiled, and in my state blocks account whenever I click "view on nanode" I still get "unknown block"
