### ISSUE TITLE
Account history issue

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#279]
Sometimes a send is displayed as receive, with the sending account address as recipient. Not sure how to trigger this. Here is  send with a refund after:

 ![schermata-20-23-29-53](https://user-images.githubusercontent.com/10681413/40283890-3b1e0c14-5c86-11e8-90cb-9c0b23ab2ecb.png)

"Repair" resolves the wrong display.

**Comment by Stormtv** [comment]
Yeah I noticed this in https://github.com/getcanoe/canoe/issues/268 but wasn't able to replicate it. Maybe repair is what is breaking it

**Comment by stefonarch** [comment]
It definitelz happens often. Need to find out how to trigger it.

**Comment by stefonarch** [comment]
Ok, thanks to one who wrote this on discord:
* It happens mostly (only?) if using "refund"
* it can invert history  display icons send><receive immediately
* sometimes all ok but restarting canoe both are displayed as receives.
* when overall history is ok it affects only the refund send probably, showing it as received
* there is the "refund button" presenti in historyon  the send txn.... which sends funds to the same account
* it never fixes by itself (needs repair)

**Comment by Stormtv** [comment]
Solved it https://github.com/getcanoe/canoe/commit/d70b75764bdaa4756a0786870f058a2d5db3daaa

**Comment by ceddup** [comment]
Good one !
