### ISSUE TITLE
Onboarding: TOS agreeing UX enhancements

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#28]
The pop-up that appears from the bottom in the last step needs some improvement from a UX point of view.

The step immediately before agreeing to the TOS is the user checking two checkboxes that are ticked by tapping anywhere on the body of the list element.

However tapping on the list element in TOS agreement does nothing, and there is no indication that TOS is clickable.

### Suggestions way forward:

1- Make the body of the TOS element a trigger to check the box. 
2- Add an underlined link after the sentence (View Term of Service)
3- TOS popping up animation is too slow. Fiddle with faster animation speeds.

**Comment by gokr** [comment]
I am not even sure we want all that stuff?

**Comment by rtaibah** [comment]
I think the first two checkpoints are important. Users need to understand the responsibility they have in managing their own wallet. As for the TOS part I think it provides a thin legal cover for us, which I don't mind taking.

In any case it's a low priority issue at this stage. We can fix later.

**Comment by Stormtv** [comment]
Unfortunately, I couldn't fix the issue of being able to click the label of the checkbox for the ToS.

The issues lies in the ionic framework, there are multiple reported issues that people have encountered and the way it is currently setup is the recommended solution.
https://forum.ionicframework.com/t/how-to-have-a-link-in-checkbox-label/4367/2

Overall this PR fixes the URL not being underlined and fixes the issue with the long delay on the ToS appearing. Let me know what you guys think!
