### ISSUE TITLE
QR code amount difference between official Nano wallets and Canoe

### ISSUE THREAD

**Issue by pedrovhb** [getcanoe/canoe#282]
Hi!

The official Nano app and nanowallet.io treat amounts in QR codes quite differently from Canoe.

Whereas Canoe seems to assume the amount is in raw, the official wallets treat the value as Nano.

For example, the following code, generated by nanowallet.io for 1000000000000000000000000000 Nano:

![0_001_nano](https://user-images.githubusercontent.com/3419601/41204219-381fb6ba-6cb8-11e8-848e-f3ab371d4ad1.png)

Which contains the following:

`xrb:xrb_1zaau9ebjawc59ykemhdwfd4s4cu91b5pk9o64nu81uuqqk5hfdjynsmozw5?amount=1000000000000000000000000000`

Results in a 0.01 Nano transaction in the Canoe app, and "Your balance is insufficient" (unfortunately) in the official app. Using reasonable Nano amounts results in a 0.00 Nano transaction in Canoe.

I think it'd be sensible for Canoe to agree with the official wallets.

**Comment by Stormtv** [comment]
Hey we are following the qr standard of using nano is raw in QR codes as dictated by the official documentation https://developers.nano.org/docs/uri-qr-code-standard/#send

**Comment by pedrovhb** [comment]
Right. I'll try to contact them separately. 

I'm closing this issue then. Thanks for the fast responses and the great app!
