### ISSUE TITLE
Weird text when clicking "Donate to Canoe"

### ISSUE THREAD

**Issue by Jiikuy** [getcanoe/canoe#283]
Version: 0.9.10 (Google Play)
Android 7.0

When I click the Donate to Canoe button in the settings, instead of showing the name of the contact, it just says
```
@[object Object]
```
Here is a screenshot:
![](https://i.imgur.com/ZvLVNGS.jpg)

**Comment by stefonarch** [comment]
It's a thingy left from the alias feature, maybe there is already an issue open but couldn't find it @Stormtv
