### ISSUE TITLE
Unable to scan QR code

### ISSUE THREAD

**Issue by geft** [getcanoe/canoe#287]
I tried getting a friend to scan my QR code but it generates a pop-up message that says something like "xrb:xrb_.... is not a valid seed QR code" or something like that. I didn't get a screenshot. Any idea why?

**Comment by stefonarch** [comment]
There are scan implementations around that doesn't accept the [standard](https://github.com/nanocurrency/raiblocks/wiki/URI-and-QR-Code-Standard), could be this that it wanted without xrb: prefix.

Canoe handles well also non-standard QR code (without xrb:) but if it's as I suspect you should file a bug   on the other wallet.

**Comment by geft** [comment]
Sorry, I should clarify. We are both using Canoe (the latest one updated today).

**Comment by geft** [comment]
It's the address implementation (2nd one in your link). The QR code is shown by the Receive tab.

**Comment by geft** [comment]
https://imgur.com/a/CWi3dlf

Here's a screenshot of my phone. Not sure if it was my friend's phone or my address that's the problem.

**Comment by geft** [comment]
Is there a way to send a screenshot of the QR code to you securely?

**Comment by stefonarch** [comment]
You can use "edit" for better reading (menu in the 3 dots ...)
Below in the editor here is link to  select   or drag images
Maybe a problem of the screen resolution? 
Specify android model and version please.

**Comment by geft** [comment]
I use Redmi Note 4, MIUI 9.5.11.0 Global (Android 7.0 NRD90M), unrooted, unlocked bootloader.

**Comment by geft** [comment]
Here's a screenshot: 
![screenshot_2018-06-25-22-18-33-061_io getcanoe canoe](https://user-images.githubusercontent.com/6178389/41860278-7aa5feb0-78c8-11e8-888f-7409c89e7853.png)

**Comment by gokr** [comment]
You said something about "bad seed QR code" - that's a message you get if you are trying to scan a seed (import seed under Settings). Is he just going to the Scan tab or?

**Comment by geft** [comment]
Specifically, he was trying to send some nano to me, so he tried adding my address to his address book. He opens the add address page and I open my Receive page. He tried scanning my QR code and kept failing.

**Comment by geft** [comment]
He did use the import seed feature beforehand. Could the QR scan activity be single instance?

**Comment by geft** [comment]
I realize it is possible that after importing the seed and playing around with other tabs, I _might_ have tried to go to the settings tab and immediately tap the square icon, not realizing it's still on the import wallet page instead of the address book page.

If that's the case, sorry for wasting your time. I'll reopen the issue if I can reproduce it somehow.

**Comment by gokr** [comment]
Ok, cool - I am unsure if it's possible, but do try to reproduce it. Thanks!
