### ISSUE TITLE
Receive QR not updated after creating new wallet

### ISSUE THREAD

**Issue by severalif** [getcanoe/canoe#292]
The QR code under the Receive tab is not updated after creating a new wallet, and instead shows the QR code for the old wallet. This happened when I: 1) locked the wallet 2) created new wallet pressing "Go back to onboarding". 

I could reproduce this bug on the Desktop version 1.0.0 on MacOS.

This bug might lead to lost funds, since funds can be sent to the old account and for which the user doesn't have the seed to anymore.

**Comment by ceddup** [comment]
Could you fix it ?

Le mar. 24 juil. 2018 à 01:06, severalif <notifications@github.com> a
écrit :

**Comment by severalif** [comment]
Yeah, the address displayed below the QR code is also the old address.

I fixed it by creating a new account (so that I have two accounts in the new wallet) and switching to the second account under the Receive tab.

**Comment by stefonarch** [comment]
And also after relogin/completely closing the app?

**Comment by gokr** [comment]
Found bug and fixed it.
