### ISSUE TITLE
building canoe on Ubuntu 16.04

### ISSUE THREAD

**Issue by lonnieOST** [getcanoe/canoe#293]
Hello,

I wanted to build canoe on my Ubuntu 16.04 (x64) system as well as run the pre-built version so that I could get a feel for things.

The pre-built version from the website, I was able to easily start it up and run without any problems. I created a NANO wallet and explored things.

Then, I grabbed the canoe code (https://github.com/getcanoe/canoe) and followed the web build instructions.

When I run the web version

---------------------------------------------------------
npm install
npm start
Visit localhost:8100 to view the app, or if you have a browser running it will be opened.
------------------------------------------------------------

Then canoe comes up in the browser and asks me to create a wallet, but then just hangs after I get to the create wallet last step.

Should I be running the "canoed" daemon and other servers as well to test the web wallet?

Please advise.
Thanks

**Comment by stefonarch** [comment]
Which browser are you running? If chromium hit ctrl+shift+j to open the debug console and report where it's hanging.

**Comment by stefonarch** [comment]
![schermata-12-19-46-51](https://user-images.githubusercontent.com/10681413/44004771-7c051096-9e68-11e8-8c0a-ea2361b4b0c3.png)
Hm, same here, just rebuilt. @gokr

**Comment by gokr** [comment]
No need for running canoed or so. I will check it.

**Comment by gokr** [comment]
Don't upgrade ionic when it asks if you want to, try to stay on the old one.

**Comment by stefonarch** [comment]
Probably ubuntu 16.04 is too old to support.
