### ISSUE TITLE
Make Canoe follow official URI/QRCode standard

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#30]
See https://github.com/clemahieu/raiblocks/wiki/URI-and-QR-Code-Standard

Today we don't follow that properly, fix!

**Comment by archSeer** [comment]
Would be great because I could embed that into RaiPay for one tap payments :) no need to manually copy in the amount

**Comment by gokr** [comment]
I am quite sure most of this logic should be in incomingData.js - the redir function.

**Comment by gokr** [comment]
Ok, so these things are basically done, apart from needing testing. We support 'xrb:', 'nano:', 'raiblocks:' and also "bare accounts" in both 'xrb_' and 'nano_' form. And the amount, label, message parameters of course. In fact any parameters will be parsed out, but not used much except amount. Also, Canoe registers URL handlers for 'xrb:', 'nano:' and 'canoe:' (not sure yet what to use it for) - and this routes into same code. So one should be able to have clickable buttons etc on the web to trigger Canoe.
