### ISSUE TITLE
Problem with Canoe?

### ISSUE THREAD

**Issue by Reznor1023** [getcanoe/canoe#315]
I keep getting “this is a list of incoming send blocks for which the account holder has not yet published a receive block to complete the transaction”
I only get this with canoe, not with nano vault. I thought the problem was on the exchange but apparently not. I’ve tried the repair, but maybe it’s not been long enough.

**Comment by Reznor1023** [comment]
Will you post here when it is fixed? Love the wallet! Thx so much !

**Comment by gokr** [comment]
Oh, sorry, yeah, it's already fixed.
