### ISSUE TITLE
Mobile Wallet is stuck

### ISSUE THREAD

**Issue by Reznor1023** [getcanoe/canoe#316]
Tried to send some tokens and it is stuck in the “nodes haven’t picked it up “
Sent some from nano and it was there in minutes
I think something is wrong on the Canoe Side.

**Comment by stefonarch** [comment]
Do you use the same seed in another wallet? If yes - this is not supported yet, so you have always to run advanced > repair to fetch the "foreign" blocks in your chains.

**Comment by Reznor1023** [comment]
Oh .. I see :) . Ty!
