### ISSUE TITLE
Onboarding: Importing seed from the onboarding homepage does not work

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#32]

**Comment by rtaibah** [comment]
I believe this is failing because of this hack https://github.com/getcanoe/canoe/issues/26

@rtpg

**Comment by rtpg** [comment]
I believe this is a quick fix, I'll write something up (would really like to get some form of testing up...)

**Comment by rtpg** [comment]
Actually, I tried to test this issue without the onboarding hack, and the issue still seemed present (something about `profileServices.wallet` not being defined before being accessed). I have seen this error elsewhere too.

**Comment by gokr** [comment]
Fixed
