### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#33]
Currently the Copay fork uses Crowdin as a translation management system. Unfortunately Crowdin is too expensive for our project. We need to find a cheaper solution (preferably free.) 

Suggestions welcome!

**Comment by Stormtv** [comment]
Crowdin is suppose to be free for open source projects? Have you guys tried requesting a free license? The only credential that is missing from the requirements is that the project be at least 3 months old.
https://crowdin.com/page/open-source-project-setup-request

**Comment by rtaibah** [comment]
Thanks @Stormtv I just applied. Hopefully they waive the 3 month requirement.

**Comment by rtaibah** [comment]
That was quick...
![screen shot 2018-01-10 at 3 34 28 pm](https://user-images.githubusercontent.com/707668/34773170-cc0eae58-f61b-11e7-8b2e-6a072004309c.png)

**Comment by gokr** [comment]
I am thinking we just go with POEdit, we use this btw:

https://angular-gettext.rocketeer.be/

So going through that website and write a HOWTO on how to help with translations would be awesome if someone did.

**Comment by gokr** [comment]
Ok, so I now have a fairly good setup working with this. We use POeditor.com, my account, and I have applied for "Open source" plan, which seems to give us unlimited on all key numbers. See:

https://poeditor.com/join/project/cnSZa85DRN

One can also use poedit or other tools to edit po-files directly.

**Comment by rtaibah** [comment]
We can close this right? It is 'implemented' yeah?

**Comment by gokr** [comment]
yep
