### ISSUE TITLE
Implement password mechanism for the wallet

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#35]
#### Must haves

1- Add a section under Settings to change the password. User is asked to enter current and new password + confirmation.
2- Password should be tested against a reasonable strength password checker. (Is there a lib for that?)
3- Add a part in on-boarding ensuring the user also steps through this procedure.
4- Hook into the "unlock" screen and present the "Enter password please"

#### Nice to have

- Add a setting called "Allow to view wallet without password". And yet another "Allow to view wallet using fingerprint or PIN".

**Comment by gokr** [comment]
This goes hand in hand with moving to raiwallet code.

**Comment by gokr** [comment]
One could possibly consider fingerprint as a setting "per account".

**Comment by gokr** [comment]
Apart from the fact that changepassword doesn't yet work - this is almost done.

**Comment by gokr** [comment]
Ok, got this finally to work. Mental note to self: Don't have a $scope function and a form name with the same name, that does not work. Closing.
