### ISSUE TITLE
Stuck in UI loop on unlock via device pin (Android)

### ISSUE THREAD

**Issue by fmvjack** [getcanoe/canoe#41]
Under the following circumstance : 
- Fingerprint locking enabled
- on unlock screen where it asks to scan fingerprint

You get stuck in this loop if your fingerprint doesn't work
- on unlock screen press "Use backup"
- Type in "device pin"
- Press "continue"
- New page pops up saying "Verify your identity"
- Only button on this page you can press is "scan again"
- Takes you back to fingerprint unlock screen.

The device pin stage doesn't work/is redundant currently.

Not to be confused with the pin locking method where you set a custom pin. This is the backup option for fingerprint

**Comment by gokr** [comment]
Set this to low since we are eventually abandoning pin and fingerprint.

**Comment by gokr** [comment]
Now... Canoe's major unlock mechanism uses the password. It needs to be entered on startup for sure. to decrypt wallet. The rest is still debatable.
