### ISSUE TITLE
Currency conversion issues

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#58]
This happened before with the SKR, now I see it in USD. Perhaps we didn't squash it completely?

![screen shot 2018-01-10 at 2 07 09 pm](https://user-images.githubusercontent.com/707668/34771266-011373c4-f615-11e7-8209-8c2f0bb4e29a.png)

**Comment by gokr** [comment]
We never fixed it AFAIK. I know basically where the issue is, just lack of time

**Comment by gokr** [comment]
I know where it us, will fix eventually

Den 10 jan 2018 12:46 em skrev "Rami Taibah" <notifications@github.com>:
