### ISSUE TITLE
Add counter and maximum number of alpha testers reached

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#69]
Our current rai_node backend can handle 1000 wallets. We should set a limit in canoed and report to users when that limit is reached and the alpha is not open for more users.

**Comment by rtaibah** [comment]
What is the mechanics for this? How will we block new users once we hit the threshold? Will it be in app, or on the website?

**Comment by gokr** [comment]
Ok, not a counter - but I added a way for us to manually stop new registrations. It will cause a dialog to pop up in the app when you try to "Create Wallet". Ideally we would need a way to see number of wallets also :) and oddly I don't think RPC offers that, but a quite stop/check/restart can be done to count them.
