### ISSUE TITLE
Add the ability to receive Rai

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#7]

**Comment by gokr** [comment]
Receive page works quite good. We don't yet have feedback for actually pocketing though.

**Comment by gokr** [comment]
Unless someone knows a problem here, close?

**Comment by rtaibah** [comment]
Needs to be tested no?

**Comment by gokr** [comment]
Yes, it works :) Homepage updates properly if switched to - or if you do "pull down update" I guess, not tested that.
