### ISSUE TITLE
Write new conversion code using rateservice

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#73]
The rate conversions is a big mess right now. Lots of odd code and relies on the rate API from Bitpay which is BTC-based. We should instead:

* Make a server side service that pulls rates from cryptocompare.com (like Exodus and many others) and publish them on one topic per currency, like `rates/<currency>/current` or similar.
* Make a new rateService.js in Canoe that subscribes via MQTT for the selected alternative currency rate.
* Write new conversion code in that service

**Comment by gokr** [comment]
The rate service is up, just need to hook it in.

**Comment by gokr** [comment]
done

**Comment by ceddup** [comment]
Good job bob !
