### ISSUE TITLE
Error during iOS build: Source path does not exist: resources/canoe/ios/icon/icon-small@2x.png

### ISSUE THREAD

**Issue by frewinchristopher** [getcanoe/canoe#74]
This occurs during the ionic build from command `npm run start:ios` I'm assuming the team will have to create the iOS icons and add them to the `resources/canoe/ios/icon/` folder to solve this one.

In the meantime, has anyone had a successful build or knows a successful workaround build for canoe on iOS yet?

**Comment by gokr** [comment]
Closing this one, don't think it applies anymore.
