### ISSUE TITLE
Official Wallet not receiving very small amounts

### ISSUE THREAD

**Issue by BWagener** [getcanoe/canoe#79]
Unsure whether this is an issue with canoe wallet or something else, but maybe worth looking into.
First I transferred 0.000001 XRB from my RaiBlocks Desktop Wallet Account to Account created in Canoe Wallet.
The funds were received and I tried transferring 0.0000001 XRB back to the RaiBlocks Desktop Wallet.
I also created a transfer of the remaining 0.0000009 XRB back to the RaiBlocks Desktop Wallet.

Both transactions are pending and won't be received by my fully synchronized running Desktop Wallet.

Official RaiBlocks Desktop Wallet Account:
https://www.raiblocks.club/account/xrb_3mx89quoizcnfp4rrmb7c6jhw7bxr9k9f4yb1g4hynkxjgyjz1rio4kmppcm

Canoe Wallet Account:
https://www.raiblocks.club/account/xrb_1a457ntnjurz96zrbarukexkc4w5eo1rkfmynpndjdcr976hms8tomczqjyy

**Comment by gokr** [comment]
I wonder, did you enter the amount in the desktop wallet using decimal form? If so, that does not work (the UI for desktop wallet is "less" ideal to say the least)- it will end up sending 0! You would need to change unit under advanced, and only enter integers.

**Comment by gokr** [comment]
Hmmm, perhaps I misunderstood.

**Comment by gokr** [comment]
Aha, this is probably due to `"receive_minimum": "1000000000000000000000000"` in config.json. We actually have the same active (its default settings) on our node at getcanoe.io. If you set it lower and restart your desktop wallet, does it then receive?

**Comment by BWagener** [comment]
Thanks for looking into this!
I apologize, I did not know about this setting, following your instructions resolved the issue.

Cheers!

**Comment by gokr** [comment]
Great! We should probably lower it on getcanoe.io too. Thanks for testing!
