### ISSUE TITLE
When scanning the code for your address the QR code adds "XRB:" to the front of your address making it invalid

### ISSUE THREAD

**Issue by afort518** [getcanoe/canoe#81]
This was between two android devices.

**Comment by ThunderFD** [comment]
also make it read raiwallet receive QR codes like this one:
raiblocks:xrb_1g6uy1qzrrkf9jxo9uka4sen1dtk4m875dzayrqejrx8bn81cff9so7y5s6b?amount=12

**Comment by gokr** [comment]
These things should be fixed, and more.
