### ISSUE TITLE
Add onboarding alias and setting for it in Account setting

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#83]
Since Tyler is making an alias server for mapping an alias to an account, we need to add an optional screen in onboarding where you can select an alias for the first account. This can be skipped. When typing it should do incremental search against catalog and show green if it's not taken. Additional rules for valid names - ask Tyler (Dimination). Also, I suspect we should show the field with a "hardcoded" @ in front of it, since that's how they will be entered later in search field etc.

Under Settings one can edit attributes of each account. Under that view there should be an entry taking you to the same view as onboarding basically, to set an alias for this account.

**Comment by gokr** [comment]
Did some work on this, there is now an alias field per account and you can edit it. But not much more.

**Comment by Stormtv** [comment]
I'm going to work on this for on-boarding now that the alias server is "finished"

**Comment by Stormtv** [comment]
Fully implemented the Alias Server in Dev - Let me know if you guys find any bugs
