### ISSUE TITLE
Android: Status bar should be a slightly darker shade from the navbar

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#86]
I simple color change in config.xml

**Comment by ceddup** [comment]
I managed to change the status bar color by replacing $v-primary-color value from #1B074E to #123238 in /sass/variables.scss:17 
It changes status bar color from royal blue to the dark green allready used on the splash screen background.
Don't know if that's the darker shade you meant.

**Comment by rtaibah** [comment]
Did you test it? Cuz that's a variable that I think is used all over the
place.

You should have done it in config.xml. Can you fix please?


Rami Taibah
Tweet me @rtaibah <http://twitter.com/rtaibah>

**Comment by ceddup** [comment]
Yeah, I tried changing StatusBarBackgroundColor in config.xml:18 but nothing happens. I think v-primary-color in saas/variable.scss is just intended to let you change that :-)

**Comment by ceddup** [comment]
I, off course, tested it
