### ISSUE TITLE
Figure out all details around password timeout, petty etc

### ISSUE THREAD

**Issue by gokr** [getcanoe/canoe#95]
We have a ... mess right now in Security Preferences. We need to decide what we want and what options we leave to the user. Petty? Timeout? Do we still offer fingerprint somehow, perhaps optional per account?

The password needs to be entered at startup at least. After timeout I wanted to purge wallet and password from RAM, but that could be a paranoia setting. If people just want to:
* Use phone lock instead
* Use fingerprint instead
and so on... perhaps we should let them. Pin seems fairly useless IMHO though.

**Comment by rtaibah** [comment]
Yes it's a mess. These were ideas that we discussed, but I guess never
hashed out properly. We should remove them for now (Petty and Sneak Peak)

**Comment by ceddup** [comment]
As debated earlier on Discord, my two cents on the subject. Gokr is writting something right now that will go arround that subject.
[Security_preferences_requirements_draft.txt](https://github.com/getcanoe/canoe/files/1711634/Security_preferences_requirements_draft.txt)

**Comment by gokr** [comment]
The idea now is to implement what I outlined here: https://getcanoe.io/2018/02/11/security-in-beta.html

**Comment by gokr** [comment]
All implemented except this:

> There is also some application logic deciding when the password unlock is required:
> Max amount to send in a single send (set in user choice of currency), without requiring password
> Max amount to send during x hours (set in user choice of currency), without requiring password

Adding that as another issue and closing this one.
